service: link-station
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 128
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /link-station
          method: get
