service: link-station
frameworkVersion: "2"
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 128
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  bestLinkStation:
    handler: src/handlers/bestLinkStation.handler
    events:
      - httpApi:
          path: /best-link-station
          method: post

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "yarn"
    includeModules: true
  serverless-offline:
    httpPort: 4000
